project:
  type: website
  output-dir: docs

website:
  title: "BU MA665 MA666"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: introduction.qmd
        text: Introduction
      - href: IF.html
        text: I&F
      - href: HH.html
        text: HH
      - href: Perceptron.html
        text: Perceptron
      - href: Backpropagation.html
        text: Backprop


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



