project:
  type: website
  output-dir: docs

render:
  ignore:
    - Dont-Sync-2024

website:
  title: "BU MA665 MA666"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Introduction.html
        text: Introduction
      - href: IF.html
        text: I&F
      - href: HH.html
        text: HH
      - href: Perceptron.html
        text: Perceptron
      - href: Backpropagation.html
        text: Backprop
      - href: Regression.html
        text: Regression
      - href: Rhythms_1.html
        text: Rhythms 1


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



