project:
  type: website
  output-dir: docs

website:
  title: "BU MA665 MA666"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: IF.html
        text: IF


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



